FROM python:3.6-alpine
MAINTAINER Mike Ryan "mikeryan56@gmail.com"
EXPOSE 5000
ENV VIRTUAL_HOST sufee-admin.devsetgo.com
ENV LETSENCRYPT_HOST sufee-admin.devsetgo.com
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
CMD ["gunicorn", "-c", "gunicorn_cfg.py", "sufee:app"]